### ISSUE TITLE
[Bug]: Method invocation failed because [System.Int32] does not contain a method named 'ToLower'.

### ISSUE THREAD

**Issue by OfficialEsco** [Trenly/winget-pkgs#133]
### Brief description of your issue

Just updated WinRAR Beta to 6.10.3 and got this error:
```
InvalidOperation: C:\Users\User\GitHub\winget-pkgs\Tools\YamlCreate.ps1:112
Line |
 112 |      [string]$_.ToLower()
     |      ~~~~~~~~~~~~~~~~~~~~
     | Method invocation failed because [System.Int32] does not contain a method named 'ToLower'.
```
This is most likely caused by WinRAR having a file extension `001` which got removed during the upgrade, i'm guessing ToLower fails when there is no letters

### Steps to reproduce

```
Selection: 2

[Required] Enter the Package Identifier, in the following format <Publisher shortname.Application shortname>. For example: Microsoft.Excel
PackageIdentifier: RARLab.WinRAR.Beta

[Required] Enter the version. for example: 1.33.7
Version: 6.10.3


There may already be a PR for this change. Would you like to continue anyways?
RARLab.WinRAR.Beta version 6.10.3 - https://github.com/microsoft/winget-pkgs/pull/37513
  [Y] Yes
  [N] No

Enter Choice (default is 'N'): y
Found Existing Version: 6.10.2
Installer Entry #1:

        InstallerLocale: en-US
        Architecture: x64
        InstallerType: exe
        Scope: machine


[Required] Enter the download url to the installer.
Url: https://www.rarlab.com/rar/winrar-x64-610b3.exe
Installer Entry #2:

        InstallerLocale: en-US
        Architecture: x86
        InstallerType: exe
        Scope: machine


[Required] Enter the download url to the installer.
Url: https://www.rarlab.com/rar/winrar-x32-610b3.exe

Yaml file created: C:\Users\User\GitHub\winget-pkgs\manifests\r\RARLab\WinRAR\Beta\6.10.3\RARLab.WinRAR.Beta.locale.en-US.yaml
InvalidOperation: C:\Users\User\GitHub\winget-pkgs\Tools\YamlCreate.ps1:112
Line |
 112 |      [string]$_.ToLower()
     |      ~~~~~~~~~~~~~~~~~~~~
     | Method invocation failed because [System.Int32] does not contain a method named 'ToLower'.


Yaml file created: C:\Users\User\GitHub\winget-pkgs\manifests\r\RARLab\WinRAR\Beta\6.10.3\RARLab.WinRAR.Beta.installer.yaml

Yaml file created: C:\Users\User\GitHub\winget-pkgs\manifests\r\RARLab\WinRAR\Beta\6.10.3\RARLab.WinRAR.Beta.yaml
Manifest validation succeeded.


Do you want to submit your PR now?
  [Y] Yes
  [N] No
```

### Expected behavior

No error 🤡

### Actual behavior

Error 🤡

### Environment

```shell
YamlCreate.ps1 version 2.0.4
```

**Comment by Trenly** [comment]
Looks like it might just be a case of missing parens.
I’m not at my computer right now, but if you try
`([string]$_).ToLower()` I bet it will work

**Comment by OfficialEsco** [comment]
Yes and no, `001` turned into `"1"`

**Comment by Trenly** [comment]
> Yes and no, `001` turned into `"1"`

Interesting. What about `(”$_”).ToLower()`, same thing?

**Comment by OfficialEsco** [comment]
Yurp

**Comment by Trenly** [comment]
> Yurp

I’ll look at it more

**Comment by Trenly** [comment]
Interesting. Seems like its some bug before it even gets to casting it as a string. Do you know which specific property its trying to cast and is failing?

**Comment by Trenly** [comment]
I don't think this is a YamlCreate bug, I think it's a bug with the manifest. Because the yaml parser itself treats `001` as an integer, when the file is loaded into the script using powershell-yaml, it is seen as an integer there too and interpreted as `1` from the moment the file is read. In fact, VSCode even recognizes that it is an integer (note that it isn't orange like the strings) -
![image](https://user-images.githubusercontent.com/12611259/145923025-6d2373d0-d8a1-4db9-b859-2dffd79e5268.png)

Because this is an inherent property of the yaml language that it should be treated as an integer, it needs to be wrapped with single quotes to be treated like a string. I don't have any way to validate it, but I would even be willing to bet that winget sees it as `1` since it isn't wrapped in the single quotes.

The proper manifest value for the extensions should be `'001'`
![image](https://user-images.githubusercontent.com/12611259/145923368-65cf5d01-00b9-458d-81f8-695e7d562477.png)

**Comment by OfficialEsco** [comment]
ooooooo, i was wondering why it was green instead of orange, so we'll be fixing at least 2 bugs with one stone then? 🤔

**Comment by Trenly** [comment]
¯\_(ツ)_/¯ 

I can't guarantee that putting it in quotes will fix anything on the client side, but it seems likely. I'd be curious to know how wingetcreate handles integers when creating/updating

Marking as resolved since this is a manifest issue.
