### ISSUE TITLE
[New Feature]: Get FileName from download item

### ISSUE THREAD

**Issue by OfficialEsco** [Trenly/winget-pkgs#145]
### Description of the new feature/enhancement

YamlCreate currently fails to detect the InstallerType when its a redirect url

### Proposed technical implementation details (optional)

https://hodgkins.io/download-file-with-powershell-without-renaming

```
$download = Invoke-WebRequest -Uri "https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWrxrH"
$content = [System.Net.Mime.ContentDisposition]::new($download.Headers["Content-Disposition"])
$content.FileName
Microsoft.RDInfra.RDAgentBootLoader.Installer-x64.msi
```
However this method miiight cause double download? and its another and slower download method...

**Comment by vedantmgoyal2009** [comment]
I guess we can use first use the `HEAD` method and get the `Content-Disposition` Header, and then download the file using the normal method. That means, https://github.com/microsoft/winget-pkgs/blob/dddcb4d5ce0c169cccea45407cc326f1d4b85356/Tools/YamlCreate.ps1#L356 should be:
```powershell
$_Filename = ((Invoke-WebRequest -Uri "https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWrxrH" -Method Head -UseBasicParsing).Headers.'Content-Disposition' | Select-String -Pattern "(?<=filename=).*").Matches.Value
```

@Trenly might have better methods, as always, since he is gone too advanced in PowerShell.

**Comment by Trenly** [comment]
We’ve tried this before, I’m certain of it. It caused more urls to be unavailable. I’ll see if I can find the discussion about it, but I know that I tried it before and it was worse

**Comment by Trenly** [comment]
Found it -
https://github.com/Trenly/winget-pkgs/pull/85/commits/79fc1e953568c21eb5d2d26556a7bcb737b80ba5
