### ISSUE TITLE
"Test your Manifest in Windows Sandbox" prompt

### ISSUE THREAD

**Issue by vedantmgoyal2009** [Trenly/winget-pkgs#42]
# Brief description of your issue

I am still being prompted for testing my manifests in Windows Sandbox after adding `AlwaysTestManifests: false` in YamlCreate script settings.

# Steps to reproduce

1. Add `AlwaysTestManifests: false` in Settings.yaml.
2. Create or update any manifest using the script.
3. The script stills prompts you for testing the manifest in Sandbox.

# Expected behavior

The script should **skip** "Test your Manifest in Windows Sandbox" prompt as the documentation says:
```
# This setting allows you to **skip the prompt** to test your manifest in windows sandbox
# If this value is set to true, all manifests will be tested by default
AlwaysTestManifests: false
```

# Actual behavior

The script still prompts and waits for the user to enter choice.

# Screenshot

![image](https://user-images.githubusercontent.com/83997633/134300075-6f076ce2-4aea-4911-8671-b3a5bd361a56.png)

**Comment by Trenly** [comment]
This isn't a bug. As worded in the documentation, it only suppresses the prompt if the value is set to "true". If it is set to false, it will not suppress the prompt. Perhaps the documentation should be a bit more clear, but as coded, the feature is working as I had originally intended, since there may be a time when a user wants to test a manifest if they are not testing them by default.

I can re-work this setting to have options for always testing and never testing, if that would be more beneficial
