### ISSUE TITLE
Advanced Modes / Dev Modes

### ISSUE THREAD

**Issue by Trenly** [Trenly/winget-pkgs#57]
# Description of the new feature/enhancement
Add "Developer Modes" which can be accessed through the enablement of a setting

# Proposed technical implementation details (optional)
* Add the setting "EnableAdvancedOperations"
* Add mode for moving a manifest
  * Requests package identifier & version from
  * Requests package identifier & version to
  * Moves the package
    * Updates`PackageIdentifier` in all applicable files
    * Updates `PackageVersion` in all applicable files
  * Creates PR
  * Deletes old package
  * Creates PR
* Add mode for auto update static URL's
  * Requests package identifier & version
  * Copies manifests exactly
  * Updates InstallerSha256 hashes automatically
  * Updates SignatureSha256 where applicable
  * Updates ProductCode where applicable
  * Updates PackageFamilyName where applicable
  * Deletes old package

**Comment by jedieaston** [comment]
Note for moving a manifest, you'll need some logic there to deal with GitHub's API restrictions (they're kind of obtuse, 5000 GraphQL hits in an hour I think but since every API call does multiple hits...). When I've done it, I just have it retry every five minutes until `gh pr create` returns 0, but maybe you want something more fancy.

**Comment by Trenly** [comment]
> Note for moving a manifest, you'll need some logic there to deal with GitHub's API restrictions (they're kind of obtuse, 5000 GraphQL hits in an hour I think but since every API call does multiple hits...). When I've done it, I just have it retry every five minutes until `gh pr create` returns 0, but maybe you want something more fancy.

Thanks for the note; I think for the purposes of the script, it doesn’t have to be very resilient. I’m still not sure if that mode is a good idea. Still thinking about the best way to inplement it

**Comment by vedantmgoyal2009** [comment]
> * Add mode for moving a manifest
>   
>   * Requests package identifier & version from
>   * Requests package identifier & version to
>   * Moves the package
>     
>     * Updates`PackageIdentifier` in all applicable files
>     * Updates `PackageVersion` in all applicable files
>   * Creates PR
>   * Deletes old package
>   * Creates PR

I don't think this should be there in YamlCreate since it is made for contributors and too many modes would confuse a "new" user since he wouldn't be knowing what he's doing. Your script is already there for moving packages from one package identifier to another.

> * Add mode for auto update static URL's
>   
>   * Requests package identifier & version
>   * Copies manifests exactly
>   * Updates InstallerSha256 hashes automatically
>   * Updates SignatureSha256 where applicable
>   * Updates ProductCode where applicable
>   * Updates PackageFamilyName where applicable
>   * Deletes old package

I think this has been already implemented in -AutoUpgrade switch.
