### ISSUE TITLE
Automatically find available information from installer

### ISSUE THREAD

**Issue by vedantmgoyal2009** [Trenly/winget-pkgs#59]
# Description of the new feature/enhancement

Since we are making most of the things automatic in the script, I think we can automate the process of finding `PackageVersion`, and some other fields. We can use the logic from [PackageParser.cs](https://github.com/microsoft/winget-create/blob/main/src/WingetCreateCore/Common/PackageParser.cs) which I guess finds most of the information (like `InstallerType`, `Architecture`, `PackageVersion`, etc.) and fill it while generating the manifest.

Since @Trenly, please don't mind, but I think you are familiar with both PowerShell & C#, so you can do that pretty easily. Also, I read about running C# code directly in PowerShell and found this:
```powershell
$code = @"
using System;
namespace HelloWorld
{
	public class Program
	{
		public static void Main(){
			Console.WriteLine("Hello world!");
		}
	}
}
"@
 
Add-Type -TypeDefinition $code -Language CSharp	
iex "[HelloWorld.Program]::Main()"
```
So, I guess we can tweak the code a little and run the code directly or you can completely convert it into PowerShell code.

I may be demanding too high, but after this, we can use the script in CI/CD the same way `wingetcreate` is used and this will also greatly reduce the chance of the wrong `PackageVersion`, `Publisher`, `InstallerType`, or `InstallerSwitches`.

**Comment by Trenly** [comment]
Probably possible, but I’m not sure how to get the PackageParser.cs component integrated with the powershell script. 

It seems like it would be difficult to manage a file that had both c# code and powershell code in it, not to mention the amount of bugs integrating multiple languages in a single file can create.

I have a feeling that wingetcreate will become much more fully-featured as time goes on. So converting it entirely to powershell code might not provide a huge amount of benefit. Some things may not even be possible in powershell due to the incredible amount of power C# has.

I’ll keep this enhancement in cosideration, but it probably won’t be at the top of my priority list

**Comment by vedantmgoyal2009** [comment]
Yes, `wingetcreate` has only one small thing because of which I cannot use it. You can see winget-create#177 for what I actually wanted.

**Comment by jedieaston** [comment]
I think YamlCreate.ps1 should stay separate from wingetcreate as much as possible. I thought the reason it was being updated was for things where wingetcreate wasn't friendly/useful.

**Comment by Trenly** [comment]
> I think YamlCreate.ps1 should stay separate from wingetcreate as much as possible (i.e. no calling into wingetcreate). I thought the reason it was being updated was for things where wingetcreate wasn't friendly/useful.

Agreed
