### ISSUE TITLE
Parameter to give Installer URLs in Quick Update Mode

### ISSUE THREAD

**Issue by vedantmgoyal2009** [Trenly/winget-pkgs#65]
# Description of the new feature/enhancement

After #64 is merged, we can use:
```
.\YamlCreate.ps1 -PackageIdentifier <PackageIdentifier> -PackageVersion <PackageVersion> -Mode <1..5>
```
Can we also add a `-Urls` Parameter so that we can run YamlCreate.ps1 in unattended mode. 

# Proposed technical implementation details (optional)
```
.\YamlCreate.ps1 --Urls <installer-url-1> <installer-url-2> <installer-url-3>
```
OR (if an array is passed)
```
.\YamlCreate.ps1 --Urls $installer_urls_array
```
Also, I think that it can be confusing for I'll suggest enabling it only when `EnableDeveloperOptions` is set to true.

**Comment by vedantmgoyal2009** [comment]
@Trenly Is the array thing possible?

**Comment by Trenly** [comment]
This isn’t possible in powershell, since we can’t guarantee that the installers will always be read in the same order. Wingetcreate avoids this issue by checking every URL and doing its best to match it with the installer, but it isn’t perfect and does sometimes fail.

**Comment by vedantmgoyal2009** [comment]
> This isn’t possible in powershell, since we can’t guarantee that the installers will always be read in the same order. 

Well, I can guarantee. I have upgraded a couple of packages and observed that myself. When there are large installers and they take time to download, I schedule keypresses and the manifests is submitted automatically.

With the limitations of powershell, this would be too much to implemet at this time

Hmm. Then, I will have to look for any workaround so I will have to build a function that does the sorting of URLs in the array automatically.

**Comment by Trenly** [comment]
> Well, I can guarantee. I have upgraded a couple of packages and observed that myself. 

I would disagree, as I have seen where it isn't in the same order as the manifest. The way that powershell-yaml interprets the installers is as an array of dictionary objects. Think `@( @{}; @{}; @{} )`. Based on what I have seen, it reads the dictionaries into memory and then stores them in the array. So, if you have 3 installers in a manifest, and one of the installers takes longer to read for whatever reason (maybe an extra key, maybe a slightly longer URL, maybe just randomly gets processed by a slower core on your CPU, etc.) then it _can_ be placed later in the array of installers. Granted this isn't a common occurrence, but I've seen it happen.

> Also what is the best thing about this when there are large installers and they take time to download, I schedule keypresses and the manifests is submitted automatically.

Automation can be very useful, but it can also be dangerous. Look at how often wingetbot tries to delete manifests that are working just fine because it either times out when downloading the installer or the website blocks bots. Not to say that automation shouldn't be done, but just that you have to be aware of edge cases any time you automate anything.

> Hmm. Then, I will have to look for any workaround so I will have to build a function that does the sorting of URLs in the array automatically.

My best suggestion for a workaround would be to create a worker script that calls YamlCreate. The flow would look something like this -
* Call the worker script with the Package.Identifier Package.Version and URL's that you want
* The worker script will find the Last version of Package.Identifier and modify the URL's only, then save the files
* The worker script can then call `YamlCreate.ps1 Package.Identifier Package.Version -AutoUpgrade`
* Don't use the autosubmit in YamlCreate
* Have your worker script restore the deleted manifest files
* Have your worker script commit the remaining changes and submit the PR

**Comment by vedantmgoyal2009** [comment]
> I would disagree, as I have seen where it isn't in the same order as the manifest. The way that powershell-yaml interprets the installers is as an array of dictionary objects. Think @( @{}; @{}; @{} ). Based on what I have seen, it reads the dictionaries into memory and then stores them in the array. So, if you have 3 installers in a manifest, and one of the installers takes longer to read for whatever reason (maybe an extra key, maybe a slightly longer URL, maybe just randomly gets processed by a slower core on your CPU, etc.) then it can be placed later in the array of installers. Granted this isn't a common occurrence, but I've seen it happen.

Oh, because I work on a fast machine, I did not experience it.

> Automation can be very useful, but it can also be dangerous. Look at how often wingetbot tries to delete manifests that are working just fine because it either times out when downloading the installer or the website blocks bots. Not to say that automation shouldn't be done, but just that you have to be aware of edge cases any time you automate anything.

I am working on automatically updating packages that are shipped through GitHub Releases. I will be happy if you would like to contribute to that once I complete it (https://github.com/vedantmgoyal2009/winget-pkgs-automation). 

> My best suggestion for a workaround would be to create a worker script that calls YamlCreate. [...]

I will see if it would work in my case. Not much difficult to implement it.

**Comment by Trenly** [comment]
> > I would disagree, as I have seen where it isn't in the same order as the manifest. The way that powershell-yaml interprets the installers is as an array of dictionary objects. Think @( @{}; @{}; @{} ). Based on what I have seen, it reads the dictionaries into memory and then stores them in the array. So, if you have 3 installers in a manifest, and one of the installers takes longer to read for whatever reason (maybe an extra key, maybe a slightly longer URL, maybe just randomly gets processed by a slower core on your CPU, etc.) then it can be placed later in the array of installers. Granted this isn't a common occurrence, but I've seen it happen.
> 
> Oh, because I work on a fast machine, I did not experience it.
> 
> > Automation can be very useful, but it can also be dangerous. Look at how often wingetbot tries to delete manifests that are working just fine because it either times out when downloading the installer or the website blocks bots. Not to say that automation shouldn't be done, but just that you have to be aware of edge cases any time you automate anything.
> 
> I am working on automatically updating packages that are shipped through GitHub Releases. I will be happy if you would like to contribute to that once I complete it (https://github.com/vedantmgoyal2009/winget-pkgs-automation).
> 
> > My best suggestion for a workaround would be to create a worker script that calls YamlCreate. [...]
> 
> I will see if it would work in my case. Not much difficult to implement it.

Another idea I had; Because of how the autoupdate works by not deleting if the version is equal to the last version, the logic could be simplified even more
* Copy previous version forward to new version folder
* Update URL's in the file
* Run YamlCreate with the autoupdate option
* Submit PR using YamlCreate
